# Generated by Django 4.0.4 on 2022-05-19 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart_shipment', '0002_initial'),
        ('store', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='costumer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='user.customeraddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cart_shipment.deliverytype'),
        ),
        migrations.AddField(
            model_name='deliverystatus',
            name='catalogue_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cart_shipment.deliverystatuscatalogue'),
        ),
        migrations.AddField(
            model_name='deliverystatus',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart_shipment.order'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart_shipment.cart'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='sup_pr_detail_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='store.supplierproductdetail'),
        ),
        migrations.AddField(
            model_name='cart',
            name='customer_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.customer'),
        ),
        migrations.AddField(
            model_name='cart',
            name='delivery_address_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='user.customeraddress'),
        ),
        migrations.AddField(
            model_name='cart',
            name='delivery_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cart_shipment.deliverytype'),
        ),
        migrations.AddField(
            model_name='cart',
            name='sup_pr_detail_id',
            field=models.ManyToManyField(through='cart_shipment.CartItem', to='store.supplierproductdetail'),
        ),
    ]
