# Generated by Django 4.0.4 on 2022-06-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_shipment', '0004_alter_cart_delivery_address_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='last_update_date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
