# Generated by Django 4.0.4 on 2022-06-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_shipment', '0005_alter_cart_last_update_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
