# Generated by Django 4.0.4 on 2022-06-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_shipment', '0007_alter_order_customer_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytype',
            name='fee',
            field=models.IntegerField(default=0),
        ),
    ]
