# Generated by Django 4.0.4 on 2022-06-15 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_shipment', '0008_deliverytype_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='costumer_id',
            new_name='customer',
        ),
    ]
