# Generated by Django 4.0.4 on 2022-06-15 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_comment_rate'),
        ('cart_shipment', '0009_rename_costumer_id_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_id',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sup_pr_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='store.supplierproductdetail'),
            preserve_default=False,
        ),
    ]
