# Generated by Django 4.0.4 on 2022-05-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_comment_dislike_alter_comment_like'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='supplierproductitem',
            constraint=models.UniqueConstraint(fields=('supplier', 'product'), name='unique product for supplier'),
        ),
    ]
