# Generated by Django 4.0.4 on 2022-06-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
