# Generated by Django 4.0.4 on 2022-06-09 20:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_paymentrecord_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
