# Generated by Django 4.0.4 on 2022-06-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_paymentrecord_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='id',
            field=models.UUIDField(default=243647847739922, editable=False, primary_key=True, serialize=False),
        ),
    ]
