# Generated by Django 4.0.4 on 2022-06-14 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_paymentrecord_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentrecord',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='paymentrecord',
            old_name='type_id',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='paymentrecorddetail',
            old_name='record_id',
            new_name='record',
        ),
        migrations.RenameField(
            model_name='paymenttypedatakey',
            old_name='type_id',
            new_name='type',
        ),
    ]
