# Generated by Django 4.0.4 on 2022-06-15 22:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_rename_order_id_paymentrecord_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
