# Generated by Django 4.0.5 on 2022-06-29 13:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WalletSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_customer', models.BooleanField(default=False)),
                ('is_suplier', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='شماره تلفن را به درستی وارد کنید', regex='^09\\d{9}$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('national_id', models.CharField(max_length=12, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('shop_name', models.CharField(max_length=255, null=True)),
                ('permission', models.BooleanField(default=False)),
                ('supplier_rate', models.FloatField(null=True)),
                ('supplier_rate_sum', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Withdrawal', 'Withdrawal'), ('Credit', 'Credit')], default='Withdrawal', max_length=50)),
                ('wallet_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='User.walletsupplier')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Withdrawal', 'Withdrawal'), ('Credit', 'Credit')], default='Withdrawal', max_length=50)),
                ('wallet_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='User.walletcustomer')),
            ],
        ),
        migrations.AddField(
            model_name='walletsupplier',
            name='supplier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User.supplier'),
        ),
        migrations.AddField(
            model_name='walletcustomer',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User.customer'),
        ),
        migrations.CreateModel(
            name='AddressSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('province', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='AddressCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('province', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.customer')),
            ],
        ),
    ]
