# Generated by Django 4.0.4 on 2022-05-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='location_lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
